# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1152c0e35e0a71e7a9cb642760c296adb61ef63167ce2fb3e3236614464ab567c23209c7035a6c0222a1f6acc2ed5adeb22cf5941d706b45894af8cf943adaf7

test:
  secret_key_base: 0a92871cbc5310210dcf33cc3de97a0b1a4df5f4690af4b18fa0622a6704ff88963eba9239bbb3494edf72775d5c5378b30cd7ca94d1b4f629f5c87b00a8f4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
